export const getInfo = () => {
  return [
    {
      projectName: "Mina DiFlor",
      companyName: "QGIS",
      type: "Mineral mapping",
      closingPrice: 1000000,
      projectStart: "Jan 13 2022",
      status: "in progress",
      personInCharge: "Olivia Rhye",
      personInChargeEmail: "olivia@untitleduei.com",
      avatar: "/mary.jpeg",
    },
    {
      projectName: "MTCH SELL",
      companyName: "Software development",
      type: "Website",
      closingPrice: 35000,
      projectStart: "Jan 13 2022",
      status: "done",
      personInCharge: "Phoenix Baker",
      personInChargeEmail: "phoenix@untitleduei.com",
      avatar: "/reben.png",
    },
    {
      projectName: "MTCH SELL",
      companyName: "Software development",
      type: "Website",
      closingPrice: 1500,
      projectStart: "Jan 13 2022",
      status: "done",
      personInCharge: "Phoenix Baker",
      personInChargeEmail: "phoenix@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "DDOG BUY",
      companyName: "Datadog Inc",
      type: "Mineral mapping",
      closingPrice: 1000000,
      projectStart: "Jan 13 2022",
      status: "in progress",
      personInCharge: "Lana Steiner",
      personInChargeEmail: "lana@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "ARKG BUY",
      companyName: "ARK Genomic",
      type: "Mineral mapping",
      closingPrice: 450000,
      projectStart: "Jan 13 2022",
      status: "cancelled",
      personInCharge: "Demi Wilkinson",
      personInChargeEmail: "demi@untitleduei.com",
      avatar: "",
    },

    {
      projectName: "DDOG BUY",
      companyName: "Datadog Inc",
      type: "Mineral mapping",
      closingPrice: 1000000,
      projectStart: "Jan 13 2022",
      status: "in progress",
      personInCharge: "Lana Steiner",
      personInChargeEmail: "lana@untitleduei.com",
      avatar: "/riki.png",
    },
    {
      projectName: "ARKG BUY",
      companyName: "ARK Genomic",
      type: "Mineral mapping",
      closingPrice: 1000000,
      projectStart: "Jan 13 2022",
      status: "cancelled",
      personInCharge: "Demi Wilkinson",
      personInChargeEmail: "demi@untitleduei.com",
      avatar: "/daniela.png",
    },
    {
      projectName: "SQ BUY",
      companyName: "MicroStrategy Inc",
      type: "Mineral mapping",
      closingPrice: 900000,
      projectStart: "Jan 13 2022",
      status: "success",
      personInCharge: "Candice We",
      personInChargeEmail: "candiec@untitleduei.com",
      avatar: "/tamila.jpg",
    },
    {
      projectName: "MSTR SELL",
      companyName: "MicroStrategy Inc",
      type: "Mineral mapping",
      closingPrice: 100,
      projectStart: "Jan 13 2022",
      status: "success",
      personInCharge: "Natali Craig",
      personInChargeEmail: "natali@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "MTCH SELL",
      companyName: "Software development",
      type: "Website",
      closingPrice: 1500,
      projectStart: "Jan 13 2022",
      status: "done",
      personInCharge: "Phoenix Baker",
      personInChargeEmail: "phoenix@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "DDOG BUY",
      companyName: "Datadog Inc",
      type: "Mineral mapping",
      closingPrice: 1000000,
      projectStart: "Jan 13 2022",
      status: "in progress",
      personInCharge: "Lana Steiner",
      personInChargeEmail: "lana@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "ARKG BUY",
      companyName: "ARK Genomic",
      type: "Mineral mapping",
      closingPrice: 450000,
      projectStart: "Jan 13 2022",
      status: "cancelled",
      personInCharge: "Demi Wilkinson",
      personInChargeEmail: "demi@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "SQ BUY",
      companyName: "MicroStrategy Inc",
      type: "E-commerce",
      closingPrice: 5000000,
      projectStart: "Jan 13 2022",
      status: "success",
      personInCharge: "Candice We",
      personInChargeEmail: "candiec@untitleduei.com",
      avatar: "/reben.png",
    },
    {
      projectName: "MSTR SELL",
      companyName: "MicroStrategy Inc",
      type: "Mineral mapping",
      closingPrice: 1000000,
      projectStart: "Jan 13 2022",
      status: "success",
      personInCharge: "Natali Craig",
      personInChargeEmail: "natali@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "DDOG BUY",
      companyName: "Datadog Inc",
      type: "Mineral mapping",
      closingPrice: 1000000,
      projectStart: "Jan 13 2022",
      status: "in progress",
      personInCharge: "Lana Steiner",
      personInChargeEmail: "lana@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "ARKG BUY",
      companyName: "ARK Genomic",
      type: "Mineral mapping",
      closingPrice: 450000,
      projectStart: "Jan 13 2022",
      status: "cancelled",
      personInCharge: "Demi Wilkinson",
      personInChargeEmail: "demi@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "SQ BUY",
      companyName: "MicroStrategy Inc",
      type: "E-commerce",
      closingPrice: 5000000,
      projectStart: "Jan 13 2022",
      status: "success",
      personInCharge: "Candice We",
      personInChargeEmail: "candiec@untitleduei.com",
      avatar: "/reben.png",
    },
    {
      projectName: "MSTR SELL",
      companyName: "MicroStrategy Inc",
      type: "Mineral mapping",
      closingPrice: 1000000,
      projectStart: "Jan 13 2022",
      status: "success",
      personInCharge: "Natali Craig",
      personInChargeEmail: "natali@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "DDOG BUY",
      companyName: "Datadog Inc",
      type: "Mineral mapping",
      closingPrice: 1000000,
      projectStart: "Jan 13 2022",
      status: "in progress",
      personInCharge: "Lana Steiner",
      personInChargeEmail: "lana@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "ARKG BUY",
      companyName: "ARK Genomic",
      type: "Mineral mapping",
      closingPrice: 450000,
      projectStart: "Jan 13 2022",
      status: "cancelled",
      personInCharge: "Demi Wilkinson",
      personInChargeEmail: "demi@untitleduei.com",
      avatar: "",
    },
    {
      projectName: "SQ BUY",
      companyName: "MicroStrategy Inc",
      type: "E-commerce",
      closingPrice: 5000000,
      projectStart: "Jan 13 2022",
      status: "success",
      personInCharge: "Candice We",
      personInChargeEmail: "candiec@untitleduei.com",
      avatar: "/reben.png",
    },
    {
      projectName: "MSTR SELL",
      companyName: "MicroStrategy Inc",
      type: "Mineral mapping",
      closingPrice: 1000000,
      projectStart: "Jan 13 2022",
      status: "success",
      personInCharge: "Natali Craig",
      personInChargeEmail: "natali@untitleduei.com",
      avatar: "",
    },
  ];
};
